{{- define "global-templates.alertmanagerconfig" -}}
{{- $global_values := .Values.global }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .alertmanagerConfigs }}
{{- if not .disabled }}
---
apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: {{ .name | required "AlertmanagerConfig name required" }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- with .route }}
  route: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .receivers }}
  receivers: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .inhibitRules }}
  inhibitRules: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .timeIntervals }}
  timeIntervals: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
