{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafkauser" -}}
{{- $global_values := .Values.global }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkausers }}
{{- if not .disabled }}
{{- $user := . }}
{{- $namespace := include "helpers.namespace" (dict "ns" ($user.namespace | default "") "overrideNs" $.Release.Namespace) }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ required "Name is required for kafkauser" $user.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $user.labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $user.annotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $user.annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- include "common.tplvalues.render" (dict "value" (required "spec is required for kafkauser" (omit $user "name" "namespace" "labels" "annotations" "disabled")) "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
