{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafka" -}}
{{- $global_values := .Values.global }}
{{- $default_values := .Values.kafka_defaults | default dict }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkas }}
{{- if not .disabled }}
{{- $kafka := . }}
{{- $customAnnotations := $kafka.annotations | default dict }}
{{- $nodePoolsEnabled := true }}
{{- if hasKey $kafka "nodePoolsEnabled" }}
{{- $nodePoolsEnabled = $kafka.nodePoolsEnabled }}
{{- end }}
{{- if $nodePoolsEnabled }}
{{- $customAnnotations = merge $customAnnotations (dict "strimzi.io/node-pools" "enabled" "strimzi.io/kraft" "enabled") }}
{{- end }}
{{- $specFields := omit $kafka "name" "namespace" "labels" "annotations" "disabled" "nodePoolsEnabled" }}
{{- $specFields = merge $specFields $default_values }}
---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ required "Name is required for kafka" $kafka.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $kafka.namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $kafka.labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $customAnnotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $customAnnotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- $specYaml := toYaml $specFields }}
  {{- $rendered := include "helpers.renderGlobalIfExists" (dict "value" $specYaml "global" $global_values) }}
  {{- tpl $rendered $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
