{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafkaconnector" -}}
{{- $global_values := .Values.global }}
{{- $default_values := .Values.kafkaconnector_defaults | default dict }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkaconnectors }}
{{- if not .disabled }}
{{- $connector := . }}
{{- $clusterRef := required "clusterRef is required for KafkaConnector" $connector.clusterRef }}
{{- $renderedClusterRef := include "helpers.renderGlobalIfExists" (dict "value" $clusterRef "global" $global_values) }}
{{- $clusterLabel := dict "strimzi.io/cluster" $renderedClusterRef }}
{{- $customLabels := merge ($connector.labels | default dict) $clusterLabel }}
{{- $customAnnotations := $connector.annotations | default dict }}
{{- $specFields := omit $connector "name" "namespace" "labels" "annotations" "disabled" "clusterRef" }}
{{- $specFields = merge $specFields $default_values }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: {{ required "Name is required for kafkaconnector" $connector.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $connector.namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $customLabels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $customAnnotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $customAnnotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- $specYaml := toYaml $specFields }}
  {{- $rendered := include "helpers.renderGlobalIfExists" (dict "value" $specYaml "global" $global_values) }}
  {{- tpl $rendered $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
