{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafkatopic" -}}
{{- $global_values := .Values.global }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkatopics }}
{{- if not .disabled }}
{{- $topic := . }}
{{- $namespace := include "helpers.namespace" (dict "ns" ($topic.namespace | default "") "overrideNs" $.Release.Namespace) }}
{{- $hasSpec := hasKey $topic "spec" }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ required "Name is required for kafkatopic" $topic.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $topic.labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $topic.annotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $topic.annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- if $hasSpec }}
  {{- include "common.tplvalues.render" (dict "value" $topic.spec "context" $) | nindent 2 }}
  {{- else }}
  {{- if hasKey $topic "partitions" }}
  partitions: {{ $topic.partitions }}
  {{- end }}
  {{- if hasKey $topic "replicas" }}
  replicas: {{ $topic.replicas }}
  {{- end }}
  {{- if $topic.config }}
  config:
    {{- include "common.tplvalues.render" (dict "value" $topic.config "context" $) | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
