{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafkabridge" -}}
{{- $global_values := .Values.global }}
{{- $default_values := .Values.kafkabridge_defaults | default dict }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkabridges }}
{{- if not .disabled }}
{{- $bridge := . }}
{{- $customAnnotations := $bridge.annotations | default dict }}
{{- $specFields := omit $bridge "name" "namespace" "labels" "annotations" "disabled" }}
{{- $specFields = merge $specFields $default_values }}
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaBridge
metadata:
  name: {{ required "Name is required for kafkabridge" $bridge.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $bridge.namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $bridge.labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $customAnnotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $customAnnotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- $specYaml := toYaml $specFields }}
  {{- $rendered := include "helpers.renderGlobalIfExists" (dict "value" $specYaml "global" $global_values) }}
  {{- tpl $rendered $ | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
