{{/*
Copyright (C) 2026 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.kafka" -}}
{{- $global_values := .Values.global }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .kafkas }}
{{- if not .disabled }}
{{- $kafka := . }}
{{- $namespace := include "helpers.namespace" (dict "ns" ($kafka.namespace | default "") "overrideNs" $.Release.Namespace) }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ required "Name is required for kafka" $kafka.name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" $namespace "global" $global_values) }}
  labels: {{- include "helpers.labels" (dict "context" $ "customLabels" $kafka.labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or $kafka.annotations $common_defaults.annotations }}
  annotations:
    {{- include "helpers.annotations" (dict "context" $ "customAnnotations" $kafka.annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  {{- include "common.tplvalues.render" (dict "value" (required "spec is required for kafka" (omit $kafka "name" "namespace" "labels" "annotations" "disabled")) "context" $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
