{{- define "global-templates.prometheusrule" -}}
{{- $global_values := .Values.global }}
{{- $common_defaults := .Values.common_defaults }}
{{- range .prometheusrules }}
{{- if not .disabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .name | required "PrometheusRule name required" }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
spec:
  groups: {{- toYaml .groups | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
