{{/*
Copyright (C) 2024 XM Cyber
Author: Devops Infra Team
*/}}

{{- define "global-templates.secret" -}}
{{- $global_values := .Values.global}}
{{- $files := .Files }}
{{- $common_defaults := .Values.common_defaults | default dict }}
{{- range .secrets }}
{{- if not .disabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "Name is required for secret" .name }}
  namespace: {{ include "helpers.prefixNamespace" (dict "namespace" .namespace "global" $global_values) }}
  labels: {{ include "helpers.labels" (dict "context" $ "customLabels" .labels "defaultLabels" $common_defaults.labels) | nindent 4 }}
  {{- if or .annotations $common_defaults.annotations }}
  annotations: {{ include "helpers.annotations" (dict "context" $ "customAnnotations" .annotations "defaultAnnotations" $common_defaults.annotations) | nindent 4 }}
  {{- end }}
type: {{ .type | default "Opaque" }}
{{- if or .data .file }}
data:
  {{- if .data }}
  {{- range $key, $val := .data }}
  {{ $key }}: |
    {{- $val | trim | nindent 4 }}
  {{- end }}
  {{- else if .file }}
    {{- include "helpers.parseYamlFile" (dict "Filename" .file "Files" $files) | trim | nindent 2 }}
  {{- end }}
{{- end }}
{{- if .stringData }}
stringData:
  {{- range $key, $val := .stringData }}
  {{- if contains "\n" $val }}
  {{ $key }}: |
    {{- $val | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $val }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}